version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = ["AppFunction=018760403092.dkr.ecr.ap-southeast-2.amazonaws.com/samapp7427b055/appfunction10acf256repo"]
