FROM public.ecr.aws/lambda/python:3.13
COPY . /home/backend
WORKDIR /home/backend

# Upgrade pip
RUN pip install --upgrade pip

# Install dependencies. Root user action just silences the warning you get because pip wants you to make a virtual environment.
RUN pip install -e . --root-user-action=ignore

CMD ["backend.main.handler"]